#!/usr/bin/env bash

# Shared helpers for SPX Voice Docker runtime config generation.

SPX_VOICE_DEPLOY_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPX_VOICE_DEPLOY_REPO_ROOT="$(cd "$SPX_VOICE_DEPLOY_LIB_DIR/../.." 2>/dev/null && pwd || true)"

spx_voice_info() {
    printf '\033[0;34m%s\033[0m\n' "$*"
}

spx_voice_success() {
    printf '\033[0;32m%s\033[0m\n' "$*"
}

spx_voice_fail() {
    printf '\033[0;31mError: %s\033[0m\n' "$*" >&2
    exit 1
}

spx_voice_project_dir() {
    if [[ -n "${SPX_VOICE_DEPLOY_PROJECT_DIR:-}" ]]; then
        printf '%s\n' "$SPX_VOICE_DEPLOY_PROJECT_DIR"
    else
        pwd
    fi
}

spx_voice_template_path() {
    local template_name="$1"
    local project_dir
    project_dir="$(spx_voice_project_dir)"

    local candidates=(
        "$project_dir/deploy/templates/$template_name"
        "$SPX_VOICE_DEPLOY_REPO_ROOT/deploy/templates/$template_name"
    )

    for path in "${candidates[@]}"; do
        if [[ -f "$path" ]]; then
            printf '%s\n' "$path"
            return 0
        fi
    done

    spx_voice_fail "Template '$template_name' not found"
}

spx_voice_is_ipv4() {
    local ip="$1"
    [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1

    local octet
    IFS='.' read -r -a octets <<< "$ip"
    for octet in "${octets[@]}"; do
        [[ "$octet" =~ ^[0-9]+$ ]] || return 1
        (( octet >= 0 && octet <= 255 )) || return 1
    done
}

spx_voice_validate_remote_runtime_env() {
    [[ "${FASTAPI_WORKERS:-}" =~ ^[1-9][0-9]*$ ]] || spx_voice_fail "FASTAPI_WORKERS must be a positive integer"
    [[ -n "${TURN_SECRET:-}" ]] || spx_voice_fail "TURN_SECRET is missing"
    [[ -n "${PUBLIC_HOST:-}" ]] || spx_voice_fail "PUBLIC_HOST is missing"
    [[ -n "${PUBLIC_BASE_URL:-}" ]] || spx_voice_fail "PUBLIC_BASE_URL is missing"
    [[ -n "${BACKEND_API_ENDPOINT:-}" ]] || spx_voice_fail "BACKEND_API_ENDPOINT is missing"
    [[ -n "${MINIO_PUBLIC_ENDPOINT:-}" ]] || spx_voice_fail "MINIO_PUBLIC_ENDPOINT is missing"
    [[ -n "${TURN_HOST:-}" ]] || spx_voice_fail "TURN_HOST is missing"
    spx_voice_is_ipv4 "${SERVER_IP:-}" || spx_voice_fail "SERVER_IP must be a valid IPv4 address"
    [[ "${PUBLIC_BASE_URL}" =~ ^https?:// ]] || spx_voice_fail "PUBLIC_BASE_URL must include http:// or https://"
    [[ "${BACKEND_API_ENDPOINT}" == "${PUBLIC_BASE_URL}" ]] || spx_voice_fail "BACKEND_API_ENDPOINT must match PUBLIC_BASE_URL"
    [[ "${MINIO_PUBLIC_ENDPOINT}" == "${PUBLIC_BASE_URL}" ]] || spx_voice_fail "MINIO_PUBLIC_ENDPOINT must match PUBLIC_BASE_URL"
    [[ "${TURN_HOST}" == "${PUBLIC_HOST}" ]] || spx_voice_fail "TURN_HOST must match PUBLIC_HOST"
}

spx_voice_render_remote_nginx_conf() {
    local project_dir="${1:-$(spx_voice_project_dir)}"
    local output_path="${2:-/dev/stdout}"
    local workers="${FASTAPI_WORKERS:-1}"
    local public_host="${PUBLIC_HOST:-localhost}"
    local template
    template="$(spx_voice_template_path "nginx.remote.conf.template")"

    {
        echo "# Auto-generated by SPX Voice config renderer. Do not edit manually."
        echo "upstream spx_voice_api {"
        echo "    least_conn;"
        local i
        for ((i = 0; i < workers; i++)); do
            echo "    server api:$((8000 + i));"
        done
        echo "}"
        awk -v public_host="$public_host" '
            {
                gsub(/__SPX_VOICE_PUBLIC_HOST__/, public_host)
                if ($0 != "__SPX_VOICE_UPSTREAM_BLOCK__") {
                    print
                }
            }
        ' "$template"
    } > "$output_path"
}

spx_voice_render_remote_turn_conf() {
    local project_dir="${1:-$(spx_voice_project_dir)}"
    local output_path="${2:-/dev/stdout}"
    local external_ip="${TURN_EXTERNAL_IP:-${SERVER_IP:-${TURN_HOST:-}}}"
    local turn_secret="${TURN_SECRET:-}"
    local template
    template="$(spx_voice_template_path "turnserver.remote.conf.template")"

    [[ -n "$external_ip" ]] || spx_voice_fail "TURN external IP/host is missing"
    [[ -n "$turn_secret" ]] || spx_voice_fail "TURN_SECRET is missing"

    awk -v external_ip="$external_ip" -v turn_secret="$turn_secret" '
        {
            gsub(/__SPX_VOICE_TURN_EXTERNAL_IP__/, external_ip)
            gsub(/__SPX_VOICE_TURN_SECRET__/, turn_secret)
            print
        }
    ' "$template" > "$output_path"
}
